package documents

type Document struct {
	Id    int64
	URL   string
	Title string
	Body  string
}

var Documents = []Document{
	{1, "https://example.com/go", "Go Programming", "Learn Go programming language and build backend applications."},
	{2, "https://example.com/python", "Python Programming", "Learn Python programming language and build applications."},
	{3, "https://example.com/rust", "Rust Programming", "Learn Rust programming language and build fast applications."},
	{4, "https://example.com/javascript", "JavaScript Programming", "Learn JavaScript programming for web development."},
	{5, "https://example.com/typescript", "TypeScript Programming", "Learn TypeScript programming for modern web applications."},
	{6, "https://example.com/java", "Java Programming", "Learn Java programming and enterprise application development."},
	{7, "https://example.com/cpp", "C++ Programming", "Learn C++ programming and systems development."},
	{8, "https://example.com/c", "C Programming", "Learn C programming for low level systems development."},
	{9, "https://example.com/backend", "Backend Development", "Learn backend development with Go and databases."},
	{10, "https://example.com/frontend", "Frontend Development", "Learn frontend development with JavaScript and TypeScript."},

	{11, "https://example.com/go-web", "Go Web Development", "Build web servers and REST APIs using Go."},
	{12, "https://example.com/go-api", "Go REST API", "Build scalable REST APIs using Go programming."},
	{13, "https://example.com/go-microservices", "Go Microservices", "Build microservices architecture using Go."},
	{14, "https://example.com/go-database", "Go Database", "Connect Go applications to PostgreSQL and MySQL databases."},
	{15, "https://example.com/go-concurrency", "Go Concurrency", "Learn goroutines channels and concurrent programming in Go."},
	{16, "https://example.com/go-testing", "Go Testing", "Learn unit testing integration testing and testing practices in Go."},
	{17, "https://example.com/go-grpc", "Go gRPC", "Build gRPC services using Go."},
	{18, "https://example.com/go-docker", "Go Docker", "Deploy Go applications using Docker containers."},
	{19, "https://example.com/go-redis", "Go Redis", "Use Redis with Go applications for caching."},
	{20, "https://example.com/go-rabbitmq", "Go RabbitMQ", "Build asynchronous applications with Go and RabbitMQ."},

	{21, "https://example.com/postgres", "PostgreSQL Database", "Learn PostgreSQL relational database fundamentals."},
	{22, "https://example.com/mysql", "MySQL Database", "Learn MySQL database administration and SQL."},
	{23, "https://example.com/redis", "Redis Database", "Learn Redis caching and in-memory data structures."},
	{24, "https://example.com/mongodb", "MongoDB Database", "Learn MongoDB document databases and NoSQL."},
	{25, "https://example.com/database-design", "Database Design", "Learn relational database design normalization and indexing."},
	{26, "https://example.com/sql", "SQL Tutorial", "Learn SQL queries joins indexes and database operations."},
	{27, "https://example.com/database-index", "Database Indexing", "Learn database indexes and query performance."},
	{28, "https://example.com/database-transactions", "Database Transactions", "Learn database transactions isolation and consistency."},
	{29, "https://example.com/database-replication", "Database Replication", "Learn database replication and high availability."},
	{30, "https://example.com/database-sharding", "Database Sharding", "Learn database sharding for scalable systems."},

	{31, "https://example.com/docker", "Docker Tutorial", "Learn Docker containers images volumes and networks."},
	{32, "https://example.com/kubernetes", "Kubernetes Tutorial", "Learn Kubernetes containers deployments services and pods."},
	{33, "https://example.com/cloud", "Cloud Computing", "Learn cloud computing infrastructure and distributed systems."},
	{34, "https://example.com/aws", "AWS Tutorial", "Learn Amazon Web Services cloud infrastructure."},
	{35, "https://example.com/gcp", "Google Cloud Tutorial", "Learn Google Cloud Platform services and infrastructure."},
	{36, "https://example.com/azure", "Azure Tutorial", "Learn Microsoft Azure cloud services."},
	{37, "https://example.com/devops", "DevOps Tutorial", "Learn DevOps automation deployment monitoring and infrastructure."},
	{38, "https://example.com/ci-cd", "CI CD Tutorial", "Learn continuous integration and continuous deployment."},
	{39, "https://example.com/linux", "Linux Administration", "Learn Linux operating systems servers and administration."},
	{40, "https://example.com/nginx", "Nginx Tutorial", "Learn Nginx web servers reverse proxy and load balancing."},

	{41, "https://example.com/networking", "Computer Networking", "Learn networking protocols TCP IP HTTP DNS and routing."},
	{42, "https://example.com/http", "HTTP Protocol", "Learn HTTP requests responses headers and status codes."},
	{43, "https://example.com/tcp", "TCP Protocol", "Learn TCP networking reliable communication and connections."},
	{44, "https://example.com/dns", "DNS Tutorial", "Learn DNS domain names records and resolution."},
	{45, "https://example.com/api", "API Design", "Learn REST API design authentication and versioning."},
	{46, "https://example.com/rest", "REST API", "Learn RESTful API architecture and HTTP methods."},
	{47, "https://example.com/grpc", "gRPC Tutorial", "Learn gRPC remote procedure calls and protobuf."},
	{48, "https://example.com/websocket", "WebSocket Tutorial", "Learn real time communication using WebSockets."},
	{49, "https://example.com/sse", "Server Sent Events", "Learn SSE real time server to client communication."},
	{50, "https://example.com/load-balancing", "Load Balancing", "Learn load balancing distributed systems and high availability."},

	{51, "https://example.com/security", "Web Security", "Learn web security authentication authorization and encryption."},
	{52, "https://example.com/jwt", "JWT Authentication", "Learn JSON Web Tokens authentication and authorization."},
	{53, "https://example.com/oauth", "OAuth Tutorial", "Learn OAuth authentication and authorization."},
	{54, "https://example.com/https", "HTTPS Security", "Learn HTTPS TLS certificates and secure communication."},
	{55, "https://example.com/encryption", "Encryption", "Learn encryption cryptography and secure communication."},
	{56, "https://example.com/password", "Password Security", "Learn password hashing authentication and security."},
	{57, "https://example.com/sql-injection", "SQL Injection", "Learn SQL injection vulnerabilities and prevention."},
	{58, "https://example.com/xss", "XSS Security", "Learn cross site scripting vulnerabilities and prevention."},
	{59, "https://example.com/csrf", "CSRF Security", "Learn cross site request forgery and security."},
	{60, "https://example.com/api-security", "API Security", "Learn API security authentication authorization and rate limiting."},

	{61, "https://example.com/algorithm", "Algorithms", "Learn algorithms data structures and computational thinking."},
	{62, "https://example.com/data-structures", "Data Structures", "Learn arrays linked lists trees graphs and hash tables."},
	{63, "https://example.com/binary-search", "Binary Search", "Learn binary search algorithms and sorted arrays."},
	{64, "https://example.com/sorting", "Sorting Algorithms", "Learn quicksort mergesort heapsort and sorting algorithms."},
	{65, "https://example.com/graph", "Graph Algorithms", "Learn graph traversal BFS DFS and shortest paths."},
	{66, "https://example.com/tree", "Tree Data Structures", "Learn binary trees AVL trees and tree algorithms."},
	{67, "https://example.com/hash-table", "Hash Tables", "Learn hash tables hashing and efficient lookup."},
	{68, "https://example.com/complexity", "Algorithm Complexity", "Learn Big O notation algorithm complexity and performance."},
	{69, "https://example.com/dijkstra", "Dijkstra Algorithm", "Learn shortest path algorithms using Dijkstra."},
	{70, "https://example.com/recursion", "Recursion", "Learn recursive programming algorithms and problem solving."},

	{71, "https://example.com/machine-learning", "Machine Learning", "Learn machine learning algorithms models and datasets."},
	{72, "https://example.com/deep-learning", "Deep Learning", "Learn deep learning neural networks and artificial intelligence."},
	{73, "https://example.com/neural-network", "Neural Networks", "Learn neural networks training and machine learning."},
	{74, "https://example.com/cnn", "CNN Tutorial", "Learn convolutional neural networks for image classification."},
	{75, "https://example.com/nlp", "Natural Language Processing", "Learn NLP text processing language models and machine learning."},
	{76, "https://example.com/transformers", "Transformers", "Learn transformer architectures attention and language models."},
	{77, "https://example.com/python-ml", "Python Machine Learning", "Build machine learning models using Python."},
	{78, "https://example.com/tensorflow", "TensorFlow Tutorial", "Build neural networks and machine learning models with TensorFlow."},
	{79, "https://example.com/pytorch", "PyTorch Tutorial", "Build deep learning models with PyTorch."},
	{80, "https://example.com/dataset", "Machine Learning Datasets", "Find datasets for machine learning and data science."},

	{81, "https://example.com/software-engineering", "Software Engineering", "Learn software engineering principles architecture and design."},
	{82, "https://example.com/design-patterns", "Design Patterns", "Learn software design patterns and object oriented programming."},
	{83, "https://example.com/clean-code", "Clean Code", "Learn clean code principles maintainability and readability."},
	{84, "https://example.com/testing", "Software Testing", "Learn unit testing integration testing and test automation."},
	{85, "https://example.com/microservices", "Microservices Architecture", "Learn microservices distributed systems APIs and service architecture."},
	{86, "https://example.com/monolith", "Monolithic Architecture", "Learn monolithic application architecture."},
	{87, "https://example.com/event-driven", "Event Driven Architecture", "Learn event driven systems messaging and asynchronous architecture."},
	{88, "https://example.com/message-queue", "Message Queues", "Learn message queues RabbitMQ Kafka and asynchronous systems."},
	{89, "https://example.com/kafka", "Apache Kafka", "Learn Kafka event streaming distributed systems and messaging."},
	{90, "https://example.com/rabbitmq", "RabbitMQ Tutorial", "Learn RabbitMQ message queues exchanges and consumers."},

	{91, "https://example.com/search-engine", "Search Engine", "Learn how search engines crawl index and retrieve websites."},
	{92, "https://example.com/inverted-index", "Inverted Index", "Learn inverted indexes posting lists and information retrieval."},
	{93, "https://example.com/search", "Search Algorithms", "Learn search algorithms indexing and information retrieval."},
	{94, "https://example.com/crawler", "Web Crawler", "Learn how web crawlers discover and download websites."},
	{95, "https://example.com/pagerank", "PageRank", "Learn PageRank link analysis and search engine ranking."},
	{96, "https://example.com/information-retrieval", "Information Retrieval", "Learn information retrieval search indexes and document retrieval."},
	{97, "https://example.com/full-text-search", "Full Text Search", "Learn full text search inverted indexes and text processing."},
	{98, "https://example.com/search-ranking", "Search Ranking", "Learn search ranking relevance scoring and information retrieval."},
	{99, "https://example.com/web-indexing", "Web Indexing", "Learn web indexing document processing and search engines."},
	{100, "https://example.com/google", "How Google Search Works", "Learn how Google search engines crawl index and rank websites."},
}
